#!/usr/bin/env python3
"""Build a deterministic fixture manifest for export/parity.py.

A parity result is only as meaningful as the input distribution it was
measured on, so the fixture set needs to be (a) real photographs, (b)
reproducible from a seed, and (c) describable in one sentence in the
report. This script produces all three.

Source: the cleanup-pairs corpus (``pairs_<subreddit>.ndjson``), whose
``gallery-pair`` records carry a ``before`` and an ``after`` image for
the same location. Sampling *pairs* rather than loose images is what
gives the fixture set its shape:

  - ``before`` frames are litter-bearing — dense scenes, many queries
    near the operating point, which is where a precision conversion can
    actually change a served answer.
  - ``after`` frames are the same location post-cleanup — sparse or
    clean, which is where a conversion could invent a detection.

A sample drawn only from one side would measure only one failure mode.

Sampling is deterministic: records are sorted by ``pair_id`` and drawn
with a seeded RNG, so re-running with the same ``--seed`` and
``--pairs`` reproduces the manifest byte for byte.

Usage::

    python scripts/build_parity_fixtures.py \\
        --corpus ../cleanup-pairs-corpus \\
        --pairs 100 --seed 0 \\
        --out reports/parity-fixtures-v1.txt
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

MANIFESTS = (
    "pairs_DeTrashed.ndjson",
    "pairs_TrashLove.ndjson",
    "pairs_coldweathercleanup.ndjson",
)


def load_pairs(corpus: Path) -> list[dict]:
    """Every complete gallery-pair with both frames present on disk."""
    rows: list[dict] = []
    for name in MANIFESTS:
        path = corpus / "data" / name
        if not path.exists():
            print(f"warning: {path} not found, skipping", file=sys.stderr)
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            rec = json.loads(line)
            if rec.get("type") != "gallery-pair":
                continue
            before, after = rec.get("before"), rec.get("after")
            if not before or not after:
                continue
            bp, ap = corpus / before, corpus / after
            if not (bp.exists() and ap.exists()):
                continue
            rows.append(
                {
                    "pair_id": rec["pair_id"],
                    "subreddit": rec.get("subreddit", "?"),
                    "before": bp,
                    "after": ap,
                }
            )
    rows.sort(key=lambda r: r["pair_id"])
    return rows


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--corpus", type=Path, required=True)
    p.add_argument("--pairs", type=int, default=100)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--out", type=Path, required=True)
    args = p.parse_args(argv)

    rows = load_pairs(args.corpus)
    if not rows:
        print("no usable pairs found", file=sys.stderr)
        return 1
    if len(rows) < args.pairs:
        print(
            f"warning: only {len(rows)} pairs available, requested {args.pairs}",
            file=sys.stderr,
        )
    rng = random.Random(args.seed)
    sample = rng.sample(rows, min(args.pairs, len(rows)))
    sample.sort(key=lambda r: r["pair_id"])

    by_sub: dict[str, int] = {}
    for r in sample:
        by_sub[r["subreddit"]] = by_sub.get(r["subreddit"], 0) + 1

    lines = [
        "# parity fixture manifest — generated by scripts/build_parity_fixtures.py",
        f"# corpus={args.corpus}  pairs={len(sample)}  seed={args.seed}",
        "# each sampled pair contributes BOTH frames: before (litter-bearing)",
        "# and after (post-cleanup). "
        + "  ".join(f"{k}={v}" for k, v in sorted(by_sub.items())),
        f"# {len(sample) * 2} images total",
    ]
    for r in sample:
        lines.append(str(r["before"].resolve()))
        lines.append(str(r["after"].resolve()))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.out}: {len(sample)} pairs -> {len(sample) * 2} images")
    print("  " + "  ".join(f"{k}={v}" for k, v in sorted(by_sub.items())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
