"""Stash R2 ingest credentials into AWS Secrets Manager.

Per the locked decision in `reference_ml_training_infra.md`, AWS Secrets
Manager is the source of truth for R2 credentials. This script reads the
local-vault files in `dregsbane-private/cloudflare/` and writes a single
JSON secret at `dregsbane/r2/beta-ingest` (us-east-1).

For local-dev convenience, also writes a `.env.r2` file in this directory
(gitignored) that exports the env vars Storage.from_env() reads. Source
it in your shell:

    set -a; source litter-detector-baseline/.env.r2; set +a   # bash
    Get-Content .env.r2 | ForEach-Object {                    # PowerShell
        if ($_ -match '^([^=]+)=(.+)$') { Set-Item "env:$($matches[1])" $matches[2] }
    }

EC2 spot training instances will read the same Secrets Manager secret via
an instance profile (provisioned by the CDK MlStack later) and populate
env vars from there.
"""

from __future__ import annotations

import json
from pathlib import Path

import boto3

VAULT = Path("C:/Users/adawg/OneDrive/Workspace/dregsbane-private/cloudflare")
REPO = Path(__file__).resolve().parent.parent

SECRET_ID = "dregsbane/r2/beta-ingest"
AWS_REGION = "us-east-1"


def main() -> int:
    account_id = (VAULT / "account-id.txt").read_text(encoding="utf-8").strip()
    api_token = (VAULT / "api-token-r2-write.txt").read_text(encoding="utf-8").strip()

    secret_body = {
        "R2_API_TOKEN": api_token,
        "R2_ACCOUNT_ID": account_id,
        "R2_CORPUS_BUCKET": "dregsbane-beta-ml-corpus",
        "R2_ARTIFACTS_BUCKET": "dregsbane-beta-ml-artifacts",
        "R2_ENDPOINT_URL": f"https://{account_id}.r2.cloudflarestorage.com",
        "_provenance": "scripts/put_r2_secret.py (bootstrap)",
        "_token_permissions": "Workers R2 Storage:Edit + Zone:Read + DNS:Edit",
        "_backend": "cf-r2-mgmt-api (Bearer auth, not S3 SigV4)",
    }

    sm = boto3.client("secretsmanager", region_name=AWS_REGION)
    try:
        sm.create_secret(
            Name=SECRET_ID,
            SecretString=json.dumps(secret_body),
            Description="R2 credentials for DregsBane ML ingest (beta).",
        )
        print(f"created new secret: {SECRET_ID}")
    except sm.exceptions.ResourceExistsException:
        sm.put_secret_value(SecretId=SECRET_ID, SecretString=json.dumps(secret_body))
        print(f"updated existing secret: {SECRET_ID} (new version)")

    # Local-dev convenience: also write .env.r2 (gitignored — .env*) so the
    # current developer's shell can source the values without re-fetching
    # from Secrets Manager every script run.
    env_path = REPO / ".env.r2"
    env_lines = [
        "# Generated by scripts/put_r2_secret.py — DO NOT commit.",
        "# Source in PowerShell:",
        "#   Get-Content .env.r2 | ForEach-Object { if ($_ -match '^([^=#]+)=(.+)$') { Set-Item \"env:$($matches[1])\" $matches[2] } }",
        f"R2_API_TOKEN={api_token}",
        f"R2_ACCOUNT_ID={account_id}",
        f"R2_BUCKET={secret_body['R2_CORPUS_BUCKET']}",
        f"R2_ENDPOINT_URL={secret_body['R2_ENDPOINT_URL']}",
    ]
    env_path.write_text("\n".join(env_lines) + "\n", encoding="utf-8")
    print(f"wrote {env_path} (gitignored)")
    print(f"\nSecrets Manager ARN reference:")
    print(f"  arn:aws:secretsmanager:{AWS_REGION}:910757112705:secret:{SECRET_ID}-*")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
